### PR TITLE
Deleted job related endpoints

### PR DESCRIPTION
**Pull request by insacuri**
# Motivation and Context

# What has changed

# How to test?

# Links

### CODE REVIEW

**Comment by insacuri** [comment]
Just testing it now.  But I'm almost certain it's going to work, so it can be reviewed now

**Comment by insacuri** [comment]
Tested it and it looks good (apart from a small config error).  But it created the printfile and tried to send it to the printfile bucket as expected.

**Review by warrenbailey — APPROVED** [review]

**Pull request merged**
