### PR TITLE
Remove feedback

### PR DESCRIPTION
**Pull request by insacuri**
# Motivation and Context
Removes all the code relating to feedback as it's something we don't use anymore.

# What has changed

# How to test?

# Links

### CODE REVIEW

**Comment by insacuri** [comment]
Tested it locally and it seemed fine, but without an EQ to complete the process, I can't be sure of the whole journey

**Review by warrenbailey — APPROVED** [review]

**Comment by warrenbailey** [comment]
Make sense to test on preprod then

**Pull request merged**
